# Gemfile for Jekyll site
source "https://rubygems.org"

# Use latest Jekyll
gem "jekyll", "~> 4.3"

# Use GitHub Pages compatible plugins
gem "github-pages", group: :jekyll_plugins

# Additional plugins
group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-redirect-from"
  gem "jekyll-avatar"
  gem "jekyll-include-cache"
end